# Generated by Django 6.0 on 2025-12-19 15:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField()),
                ('estado', models.CharField(choices=[('AGENDADA', 'Agendada'), ('CONFIRMADA', 'Confirmada'), ('EN_ATENCION', 'En Atención'), ('FINALIZADA', 'Finalizada'), ('ANULADA', 'Anulada')], default='AGENDADA', max_length=20)),
                ('numero_sesion', models.PositiveIntegerField(default=1, help_text='Número de sesión actual')),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(help_text='RUT o DNI', max_length=12, unique=True)),
                ('nombre_completo', models.CharField(max_length=150)),
                ('fecha_nacimiento', models.DateField()),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('antecedentes_medicos', models.TextField(blank=True, help_text='Cirugías, alergias, enfermedades crónicas')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tratamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=0, max_digits=10)),
                ('sesiones_totales', models.PositiveIntegerField(default=1, help_text='Cantidad de sesiones que incluye este pack')),
            ],
        ),
        migrations.CreateModel(
            name='FichaEvolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo_consulta', models.CharField(max_length=200)),
                ('subjetivo', models.TextField(help_text='Lo que relata el paciente (dolor, sensaciones)')),
                ('objetivo', models.TextField(help_text='Hallazgos físicos, rangos de movimiento, fuerza')),
                ('nivel_dolor_eva', models.PositiveIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], help_text='Escala 1 a 10')),
                ('analisis_plan', models.TextField(help_text='Diagnóstico kinesiológico y ejercicios para la casa')),
                ('proxima_sesion_sugerida', models.DateField(blank=True, null=True)),
                ('cita', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.cita')),
            ],
        ),
        migrations.CreateModel(
            name='Kinesiologo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidad', models.CharField(default='Kinesiología General', max_length=100)),
                ('registro_profesional', models.CharField(help_text='Nro de registro superintendencia', max_length=50)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='cita',
            name='kinesiologo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.kinesiologo'),
        ),
        migrations.AddField(
            model_name='cita',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='core.paciente'),
        ),
        migrations.AddField(
            model_name='cita',
            name='tratamiento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.tratamiento'),
        ),
    ]
