# Generated by Django 6.0 on 2025-12-19 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='antecedentes',
            field=models.TextField(blank=True, default='Sin antecedentes', verbose_name='Antecedentes Médicos'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='deporte',
            field=models.CharField(blank=True, default='Sedentario', max_length=100, verbose_name='Deporte/Actividad'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='diagnostico_ingreso',
            field=models.TextField(blank=True, default='En evaluación', verbose_name='Diagnóstico de Ingreso'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='direccion',
            field=models.CharField(blank=True, max_length=200, verbose_name='Dirección'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='ocupacion',
            field=models.CharField(blank=True, default='No especificada', max_length=100, verbose_name='Ocupación'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, verbose_name='Teléfono'),
        ),
    ]
