# Generated by Django 6.0 on 2025-12-19 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='deporte',
            field=models.CharField(blank=True, help_text='Deporte que practica', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='diagnostico_ingreso',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Diagnóstico Médico/Ingreso'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='direccion',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Dirección'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='institucion',
            field=models.CharField(blank=True, help_text='Isapre, Fonasa, Club, etc.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='ocupacion',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ocupación'),
        ),
    ]
