# Generated by Django 6.0 on 2025-12-19 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_paciente_antecedentes_paciente_deporte_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='prevision',
            field=models.CharField(choices=[('FONASA', 'Fonasa'), ('ISAPRE', 'Isapre'), ('PARTICULAR', 'Particular'), ('OTRO', 'Otro / Convenio')], default='PARTICULAR', max_length=20, verbose_name='Previsión'),
        ),
    ]
