# Generated by Django 6.0 on 2025-12-24 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_paciente_prevision'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='evolucion',
            field=models.TextField(blank=True, default='', verbose_name='Evolución Clínica'),
        ),
    ]
