# Generated by Django 6.0 on 2025-12-24 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_cita_evolucion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('monto', models.IntegerField(verbose_name='Monto Pagado')),
                ('metodo', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia'), ('DEBITO', 'Débito/Crédito'), ('BONO', 'Bono Fonasa/Isapre')], default='EFECTIVO', max_length=20)),
                ('cita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='core.cita')),
            ],
        ),
    ]
