# Generated by Django 6.0 on 2025-12-24 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinica',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos_clinicas/'),
        ),
        migrations.AlterField(
            model_name='clinica',
            name='direccion',
            field=models.CharField(blank=True, max_length=200, verbose_name='Dirección Comercial'),
        ),
    ]
