# Generated by Django 6.0 on 2025-12-24 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_clinica_logo_alter_clinica_direccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='detalle_prevision',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Especifique Convenio'),
        ),
    ]
